In [1]:
import numpy as np
from scipy.linalg import lu
from scipy.linalg import svd

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]
             ])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]
             ])

print('Matrix 1 \n', A)
print('\n Matrix 2 \n', B)

y = int(input('Please Choose Which Matrix do you like to decompose!: '))

if y == 1:
    if A.shape[0] == A.shape[1]:
        x = input('Please choose either Eigen or PLU decomposition: ')
        if x.lower() == 'eigen':
            value, vector = np.linalg.eig(A)
            print('Egien Vector: \n', vector)
            print('\n Egien Value: \n', value)
            q = vector
            l = np.linalg.inv(vector)
            r = np.diag(value)
            print('\n Main Matrix: \n', q.dot(l).dot(r))
        elif x.lower() == 'plu':
            P, L, U = lu(A)
            print('P Part: \n', P)
            print('\n L Part: \n', L)
            print('\n U Part: \n', U)
            print('\n Main Matrix: \n', P.dot(L).dot(U))
else:
    z = input('Please choose either SVD or QR decomposition: ')
    if z.lower() == 'QR':
        Q, R = np.linalg.qr(B, 'complete')
        print('Q Part: \n', Q)
        print('\n R Part: \n', R)
        print('\n Main Matrix: \n', Q.dot(R))
    elif z.lower() == 'SVD':
        U, S, V = svd(B)
        print('U Part: \n', U)
        print('\n S Part: \n', S)
        print('\n V Part: \n', V)


Matrix 1 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Matrix 2 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Please Choose Which Matrix do you like to decompose!: 1
Please choose either Eigen or PLU decomposition: plu
P Part: 
 [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

 L Part: 
 [[ 1.          0.          0.          0.        ]
 [ 0.07692308  1.          0.          0.        ]
 [ 0.69230769  0.33333333  1.          0.        ]
 [ 0.38461538  0.66666667 -0.64        1.        ]]

 U Part: 
 [[ 1.30000000e+01  1.40000000e+01  1.50000000e+01  1.60000000e+01]
 [ 0.00000000e+00  9.23076923e-01  1.84615385e+00  2.76923077e+00]
 [ 0.00000000e+00  0.00000000e+00 -2.84672570e-16 -5.75038592e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  5.32907052e-17]]

 Main Matrix: 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
